dazl-dev/file-services

- packages/test-kit/src/async-fs-contract.ts
- packages/test-kit/src/sync-fs-contract.ts
- packages/types/src/extended-api-async.ts
- packages/types/src/extended-api-sync.ts
- packages/utils/src/create-extended-api.ts
initial naive implementation. ignores symbolic links.
closes #17
> Implement copyDirectory

- packages/node/test/watch-service.spec.ts
- packages/resolve/README.md
- packages/test-kit/src/watch-events-validator.ts
so that latest stats can be checked
fixes #32
> test-kit: events validator accepts events provider

- packages/resolve/src/request-resolver.ts
- packages/resolve/src/types.ts
simplifies and flattens implementation
> resolve: refactor to use generators

- packages/cached/src/cached-fs.ts
- packages/directory/src/directory-fs.ts
- packages/memory/src/memory-fs.ts
- packages/node/package.json
- packages/test-kit/src/async-base-fs-contract.ts
- packages/test-kit/src/sync-base-fs-contract.ts
- packages/types/src/base-api-async.ts
- packages/types/src/base-api-sync.ts
- packages/utils/src/sync-to-async-fs.ts
> feat: mkdir options (recursive)

- packages/node/src/node-fs.ts
latest Node 10 doesn't have a warning anymore.
> node: use native fs.promises

- packages/resolve/src/request-resolver.ts
- packages/resolve/src/types.ts
> resolve: cache resolved packages

- packages/memory/src/memory-fs.ts
the new optimized Map lookup was problematic for upcoming symlink support.
reverted to the previous approach, but optimized it not not create a function per node lookup.
> refactor: ensure memory node lookup for links

- packages/cached/src/cached-fs.ts
- packages/directory/src/directory-fs.ts
- packages/memory/src/memory-fs.ts
- packages/node/src/node-fs.ts
- packages/test-kit/src/async-base-fs-contract.ts
- packages/test-kit/src/sync-base-fs-contract.ts
- packages/types/src/base-api-async.ts
- packages/types/src/base-api-sync.ts
- packages/types/src/common-fs-types.ts
- packages/utils/src/sync-to-async-fs.ts
> feat: implement fs.rmSync and fs.promises.rm

- .github/workflows/tests.yml
- package-lock.json
- packages/node/package.json
- packages/node/src/node-fs.ts
> chore!: drop Node 12; add 18

- packages/cached/src/cached-fs.ts
- packages/directory/src/directory-fs.ts
- packages/memory/src/memory-fs.ts
- packages/overlay/src/overlay-fs.ts
- packages/types/src/base-api-sync.ts
- expose from node as-is
- implement in all other fs packages
> feat: implement fs.realpathSync.native

- packages/node/src/watch-service.ts
wait for the "close" event to be emitted by the watcher before resolving that unwatch suceeded.
> fix(node): unwatch resolves when watcher is closed

- packages/commonjs/test/npm-packages.nodespec.ts
- packages/resolve/src/request-resolver.ts
- packages/resolve/src/types.ts
- packages/resolve/test/request-resolver.spec.ts
defaults to true when "target" is set to "browser"
> feat(resolve): support "module" field

- packages/commonjs/test/npm-packages.nodespec.ts
- packages/resolve/src/request-resolver.ts
- packages/resolve/src/types.ts
- packages/resolve/test/request-resolver.spec.ts
> feat(resolve)!: support "exports" field

- packages/resolve/src/request-resolver.ts
- packages/resolve/src/types.ts
- packages/resolve/test/request-resolver.spec.ts
> feat(resolve): support importing self

- packages/resolve/src/request-resolver.ts
- packages/resolve/test/request-resolver.spec.ts
while string-to-string patterns were supported, this change adds support for matching nested conditions with patterns as well.
> feat(resolve): support patterns with nested conditions

- .mocharc.js
- package-lock.json
- package.json
- packages/cached/package.json
- packages/commonjs/package.json
- packages/memory/package.json
- packages/node/package.json
- packages/overlay/package.json
- packages/resolve/package.json
- packages/test-kit/package.json
- packages/types/package.json
- packages/typescript/package.json
- packages/utils/package.json
- scripts/build.mjs
- tsconfig.base.json
- tsconfig.json
- webpack.config.js
> feat: expose cjs/esm bundles from packages

- packages/resolve/src/request-resolver.ts
- packages/resolve/test/request-resolver.spec.ts
also optimize a bit by calculating `starReplacement` once
> feat(resolve): matching without replacement

- packages/memory/src/memory-fs.ts
- packages/memory/src/types.ts
- packages/node/src/index.ts
- packages/node/test/node-fs.nodespec.ts
- packages/overlay/src/overlay-fs.ts
- packages/test-kit/src/async-base-fs-contract.ts
- packages/test-kit/src/sync-base-fs-contract.ts
- packages/types/src/base-api-async.ts
- packages/types/src/base-api-sync.ts
- packages/types/src/common-fs-types.ts
- packages/types/src/extended-api-async.ts
- packages/types/src/extended-api-sync.ts
- packages/utils/src/create-extended-api.ts
- tsconfig.base.json
using `TextEncoder`/`TextDecoder` for conversion.
closes #169
> feat(memory)!: support binary files as Uint8Array

- packages/resolve/src/request-resolver.ts
- packages/resolve/src/types.ts
- packages/resolve/test/request-resolver.spec.ts
> feat(resolve): implement support for "imports" field

- packages/cached/src/cached-fs.ts
- packages/cached/test/cached-fs.spec.ts
- packages/overlay/src/overlay-fs.ts
- packages/types/src/base-api-async.ts
- packages/types/src/common-fs-types.ts
- packages/utils/src/sync-to-async-fs.ts
pure overhead, as we aren't using it
> feat!: remove callback-based async API

- packages/node/src/node-fs.ts
- packages/node/src/recursive-fs-watcher.ts
Reverts dazl-dev/file-services#1372
> feat!: re-add linux recursive watcher Linux shim
