packages/memory/src/memory-fs.ts, packages/memory/src/types.ts, packages/memory/test/memory-fs.spec.ts
- better performance, with us deleting keys off the object (deoptimizing it)
- removed confusing shadow entries concept for easier node management
- ensure path.resolve is relative to `/` instead of cwd in node
- removed unneeded async copy mtime tests. sync is enough in this case.
- simplified copying tests. IDirectoryContents accepts absolute paths and treats them properly. less let statements.
=> memory: use Map instead of plain objects for directories

packages/node/package.json, packages/node/test/node-fs.spec.ts, packages/node/test/watch-service.spec.ts, packages/test-kit/src/async-base-fs-contract.ts, packages/test-kit/src/sync-base-fs-contract.ts, packages/test-kit/src/watch-events-validator.ts
should fix CI flakiness around ">200ms" watch service test, as both events are now verified together, instead of trying to catch the first one before the second arrives.
=> test-kit: change WatchEventsValidator::lastEvent to accept multiple events

.travis.yml, package.json, packages/memory/src/memory-fs.ts, packages/node/package.json, packages/node/src/node-fs.ts, packages/node/src/tsconfig.json, packages/node/src/watch-service.ts, packages/node/test/watch-service.spec.ts, packages/test-kit/src/async-base-fs-contract.ts, packages/test-kit/src/async-fs-contract.ts, packages/types/src/base-api-async.ts, packages/types/src/base-api-sync.ts, packages/types/src/common-fs-types.ts, packages/types/src/extended-api-async.ts, packages/utils/src/callbackify.ts, packages/utils/src/create-extended-api.ts, packages/utils/src/directory-fs.ts, packages/utils/src/sync-to-async-fs.ts, packages/utils/test/directory-fs.spec.ts, yarn.lock
- Drop node 8 support.
- Exposes all promise-based API under `promises` field (matches Node 10+).
- Node package uses Node 10's native `promises` API instead of promisifying them every time via `proper-fs`.
- Callback-style API is now exposed as well from async file systems.
- `readlink` (promise and callback style) and `readlinkSync` is now exposed as well, for better compatibility with libraries expecting Node-style API.
closes #14
=> Breaking: change API to be a real subset of Node's

packages/node/test/watch-service.spec.ts
watching parent directory gives watch events for child directories being deleted
=> node: re-enable directory removal test

packages/cached/src/cached-fs.ts, packages/cached/test/cached-fs.spec.ts
When profiling, it seems that alot of time is still wasted on statSync for non-existing files (through fileExists). Trying to use cache for those cases too
=> Enhance cached: cache stats check when file doesn't exist

packages/test-kit/src/async-fs-contract.ts, packages/test-kit/src/sync-fs-contract.ts, packages/utils/src/create-extended-api.ts
Behavior:
- more specific `error.code` checks. avoiding extra fs calls, with more errors being propagated.
- still room for improvement. could try and see if `error.code` for non-existing parent is consistent between platforms, and only ensure parent if that code was thrown.
Tests:
- test async variant (`ensureDirectory`) as well.
- avoid using `populateDirectory` during tests (it uses `ensureDirectory` on its own!).
- simplify tests for easier reading. no more trying to map objects to textual paths.
- avoid testing the stuff don't happen (file isn't being deleted; content is kept). these assertions are acceptable as regression tests (not this case). otherwise, one could test virtually anything (new directory is empty, etc).
=> refactor: ensureDirectory behavior/tests cleanups

packages/resolve/src/request-resolver.ts, packages/resolve/src/types.ts
- Using it directly allows native node fs to be provided `{ ...fs, ...path }`.
- Makes it possible to do a self validating cache.
=> resolve: statSync instead of file/directoryExists

packages/cached/src/cached-fs.ts, packages/directory/src/directory-fs.ts, packages/memory/src/error-codes.ts, packages/memory/src/memory-fs.ts, packages/memory/src/types.ts, packages/test-kit/src/sync-base-fs-contract.ts, packages/types/src/base-api-async.ts, packages/types/src/base-api-sync.ts, packages/utils/src/sync-to-async-fs.ts
- fix directory fs's handling of links pointing outside the directory.
- add contract tests to verify symlink behaviors.
- correct handling of readlink vs realpath in various places.
- avoid resoving relative link paths. happens every time a link is dereferenced.
builds upon the work at #153. further optimizes memory-fs's operation, supports/retains relative links, and fixes link handling in directory fs.
=> feat: implement symlinkSync and promises.symlink

packages/memory/src/memory-fs.ts, packages/memory/src/types.ts
creates a stats object per node, and uses that.
only creates new objects when modifying values.
=> perf: optimize memory fs's stats handling

packages/node/test/node-fs.spec.ts, packages/test-kit/src/sync-base-fs-contract.ts
instead of calling realpath on expected result.
ensures nothing funny occurs to the expected value, if realpath is misbehaving.
=> test: pass actual temp directory to contract

packages/resolve/src/request-resolver.ts, packages/resolve/src/types.ts, packages/resolve/test/request-resolver.spec.ts
When an internal package request is re-mapped to `false`, this will point to the original filePath this request pointed to.
=> feat(resolve): original path for false-remapped

packages/commonjs/src/base-cjs-module-system.ts, packages/commonjs/src/cjs-module-system.ts, packages/commonjs/test/cjs-module-system.spec.ts, packages/commonjs/test/npm-packages.nodespec.ts
- in higher-order module system factory (one provided with `fs`), it passes `fs.cwd()` for `process.cwd`.
- `process.on` is just a mocked noop.
- enabled several node specs to test this via external libs.
=> feat(commonjs): support process.on/cwd

packages/commonjs/src/base-cjs-module-system.ts, packages/commonjs/src/cjs-module-system.ts, packages/commonjs/src/types.ts, packages/commonjs/test/cjs-module-system.spec.ts, packages/commonjs/test/npm-packages.nodespec.ts, packages/webpack/test/webpack-fs.nodespec.ts
- drop processEnv and cwd options. one can simply inject process.
- re-enable sass test. no longer causes webpack to break.
=> breaking(commonjs): support injecting globals

packages/resolve/src/request-resolver.ts, packages/resolve/test/request-resolver.spec.ts
`"."` and `".."` didn't work.
`"./"` and `"../"` did. :)
=> fix(resolve): handle recursive imports to index.js

packages/commonjs/src/base-cjs-module-system.ts, packages/commonjs/test/cjs-module-system.spec.ts
pretty naive way of retaining file paths during evaluation.
works in node and chrome (probably ff too).
proper source-map support still requires investigation.
=> feat(commonjs): retain file path in module eval

packages/cached/src/cached-fs.ts, packages/directory/src/directory-fs.ts, packages/memory/src/memory-fs.ts, packages/node/src/node-fs.ts, packages/overlay/src/overlay-fs.ts, packages/resolve/src/request-resolver.ts, packages/resolve/src/types.ts, packages/test-kit/src/sync-base-fs-contract.ts, packages/types/src/base-api-async.ts, packages/types/src/base-api-sync.ts, packages/types/src/common-fs-types.ts, packages/typescript/src/create-host.ts, packages/utils/src/create-extended-api.ts, packages/utils/src/sync-to-async-fs.ts
- wrapped/polyfilled for older node versions.
- implement memory fs support.
- adjusted resolver, base-host and other abstractions to make use of the new flag
=> feat: throwIfNoEntry in stat/statSync

packages/commonjs/test/cjs-module-system.spec.ts, packages/resolve/src/request-resolver.ts, packages/resolve/src/types.ts, packages/resolve/test/request-resolver.spec.ts
- to be able to cache and invalidate resolutions fully
- might still have a small gap with the realpath of package.json files
=> feat(resolve): add visitedPaths to result

packages/test-kit/src/async-fs-contract.ts, packages/test-kit/src/sync-fs-contract.ts, packages/types/src/extended-api-async.ts, packages/types/src/extended-api-sync.ts, packages/utils/src/create-extended-api.ts
no need for this extended API, now that the base has fs.rmSync and fs.promises.rm with the force and recursive flags
=> breaking: delete removeSync and promises.remove

packages/overlay/src/overlay-fs.ts, packages/overlay/test/overlay.spec.ts
when both lowerFs and higherFs contained an item, readdir returned duplicate results.
this change fixes that by deduping results (leaving only the upperFs when `withFileTypes: true`)
=> fix(overlay): return single instance when item in both fs

packages/types/src/common-fs-types.ts, packages/utils/src/create-extended-api.ts
use `withFileTypes`, now available. this will save fs operations as well.
=> fix(find-files): avoid circularities due to links

packages/directory/src/directory-fs.ts, packages/memory/src/memory-fs.ts, packages/types/src/base-api-async.ts, packages/types/src/base-api-sync.ts, packages/utils/src/sync-to-async-fs.ts
use node's native API for node implementation, and noop for memory
=> feat: expose chmodSync and promises.chmod

packages/overlay/src/overlay-fs.ts, packages/overlay/test/overlay.spec.ts
* fixes a case when the base directory is the child directory of the path we are trying to get realpath from
=> fix(overlay): fix realpath resolution for parent dir of base dir

packages/node/src/watch-service.ts, packages/node/test/watch-service.nodespec.ts
to avoid events being emitted after unwatching a specific path, or unwatching all paths
=> fix(node): clear pending events on unwatch

packages/resolve/src/request-resolver.ts, packages/resolve/test/request-resolver.spec.ts
previously, when requesting some_package/alt, only the root package.json was listed in visitedPaths. now it will list some_package/alt/package.json if it exists
=> fix(resolve): track package.json files in dirs

packages/resolve/src/request-resolver.ts, packages/resolve/test/request-resolver.spec.ts
previously only worked in `target === "browser"`
=> fix(resolve): support "module" in "node" target

packages/resolve/src/request-resolver.ts, packages/resolve/test/request-resolver.spec.ts
when resolver finds a pattern match, we keep going over the "exports" to see if we can find `null` (for explicit file exclusion). if we do find another matching key, we should not also try to re-match string values.
=> fix(resolve): avoid re-matching subpath patterns

packages/node/src/node-fs.ts, packages/node/src/watch-service.ts
- to fix mjs target not working due to accessing __filename
- import from "node:<lib>" for clarity
=> fix(node): use cwd for case-sensitivity check

packages/memory/src/memory-fs.ts, packages/memory/src/types.ts
- if writeFile was called with a string, keep it, and use it if readFile is called with an encoding.
- smarter code would try to do it right for different encodings, but we're currently on the implicit-utf8-everwhere train.
- if contents is written as text, it will be kept as text. if someone calls readFile in binary mode, it will re-encode the text to binary per every read call.
- happy, no-conversion, path is: write as string, and read with an encoding.
=> perf(memory): avoid text conversion if possible

packages/commonjs/src/base-cjs-module-system.ts, packages/commonjs/test/cjs-module-system.spec.ts
- inject file path chain into the prefix of the error message
- ensure .json file evaluation errors have file path as well
- avoid injecting sourceURL comment to allow support for full sourcemaps
=> feat(commonjs)!: better evaluation-time error messages

packages/memory/src/memory-fs.ts, packages/node/test/node-fs.nodespec.ts, packages/test-kit/src/sync-base-fs-contract.ts, packages/types/src/base-api-sync.ts, packages/types/src/common-fs-types.ts
- implement `watch()` for memory fs
- expose native node one, as it is now supported on linux as well
=> feat: introduce native fs.watch

packages/node/src/watch-service.ts, packages/node/test/watch-service.nodespec.ts
Fixes #1186
On Windows deleting watched directory is firing event `error` which is caught by `NodeWatchService.ensureWatcher`:
```
directoryWatcher.once("error", (e) => {
this.onWatchError(e, path);
});
```
this in turn causes 2 effects:
1. `watcher.close();` in the `onWatchError`
2. debounced (by `onPathEvent`) `this.fsWatchers.delete(path);`  in the `emitEvent` method.
If `unwatchAllPaths` was invoked between these 2 effects we would enter a state when `unwatchAllPaths` can't finish.
This happened due to 
1. `unwatchAllPaths` assumes that all `this.fsWatchers` are not closed
2. `unwatchAllPaths` invokes `close` on each watcher and waits for the `close` event on all of watchers
But this can't work because  `watcher.close();` was called in the `onWatchError`, so we are left with a method …
=> fix(watch-service): remove watcher when it gets closed due to directory removal

packages/node/src/node-fs.ts, packages/node/src/recursive-fs-watcher.ts
workaround unhandled exceptions during runtime and/or close() in Node's own recursive watcher. reported upstream.
now using own implementation of recursive FSWatcher which implements the subset api file-services exposes.
=> fix(node): use own recursive watch under Linux

packages/resolve/src/request-resolver.ts, packages/resolve/src/types.ts, packages/resolve/test/request-resolver.spec.ts
remove the cache that made problems with changing content
=> fix(resolve): make browser field resolution lazy

packages/node/src/recursive-fs-watcher.ts
otherwise, it will throw and crash process when recursive watch emits an error event during class construction, and no 'error' handler was registered yet.
=> fix: async watch in recursive watcher Linux shim

.github/workflows/tests.yml
preparing for Node 24, once it releases. they are still working on v8 13.4 integration
=> ci: test on Node 23 as well

.github/workflows/tests.yml
https://nodejs.org/en/blog/release/v24.0.0
=> ci: use Node 24
